### ISSUE TITLE
Update manifest concepts page

### ISSUE THREAD

**Issue by zmitchell** [flox/floxdocs#72]
- Remove the list of manifest sections
- Add a link to the manifest reference page
- Add a short code block containing a manifest to give a minimal example (like this one shown below, but not necessarily the exact one shown below).

```toml
version  = 1

[install]
hello.pkg-path = "hello"

[options]
systems = ["aarch64-darwin", "x86_64-darwin", "aarch64-linux", "x86_64-linux"] 
```
